CREATE TABLE [dbo].[CLIENTES]
(
  [CEDULA]	VARCHAR(6) NOT NULL PRIMARY KEY,
  [NOMBRE]			VARCHAR(30) NOT NULL,
  [APELLIDO]		VARCHAR(30) NOT NULL,
  [GENERO]			VARCHAR(1) CHECK (GENERO = 'F' OR GENERO = 'M' OR GENERO = 'U'),
  [EDAD]			NUMERIC(3) NOT NULL,
  [FECHA_NACIMIENTO] DATE NOT NULL,
  [ESTADO_CIVIL] VARCHAR(1) CHECK (ESTADO_CIVIL = 'C' OR ESTADO_CIVIL = 'S' OR ESTADO_CIVIL = 'V' OR ESTADO_CIVIL = 'D')
)

CREATE TABLE [dbo].[CUENTAS]
(
  [ID_CUENTA]	VARCHAR(6) NOT NULL PRIMARY KEY,
  [ID_CLIENTE]	VARCHAR(6) NOT NULL,
  [SALDO]		NUMERIC(300) NOT NULL,
  [MONEDA]  VARCHAR(1) CHECK (MONEDA = 'D' OR MONEDA = 'C'),
  CONSTRAINT FK_CLIENTES_CUENTAS FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CEDULA)
)

CREATE TABLE [dbo].[CREDITOS]
(
  [ID_CREDITO]	VARCHAR(6) NOT NULL PRIMARY KEY,
  [ID_CLIENTE]	VARCHAR(6) NOT NULL,
  [NOMBRE]			VARCHAR(30) NOT NULL,
  [MONTO]			NUMERIC(300) NOT NULL,
  [TASA]			DECIMAL(10,3) NOT NULL,
  [CUOTA]			DECIMAL(10,3) NOT NULL,
  [FECHA_INICIO] DATE NOT NULL,
  [ESTADO]   BOOLEAN NOT NULL,
  [SALDO_OPERACION]	 NUMERIC(300) NOT NULL,
  CONSTRAINT FK_CLIENTES_CREDITOS FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CEDULA)
)

CREATE TABLE [dbo].[DIRECCIONES]
(
  [ID_DIRECCION]	VARCHAR(6) NOT NULL PRIMARY KEY,
  [ID_CLIENTE]	VARCHAR(6) NOT NULL,
  [PROVINCIA]			VARCHAR(30) NOT NULL,
  [CANTON]		VARCHAR(30) NOT NULL,
  [DISTRITO]		VARCHAR(30) NOT NULL,
  CONSTRAINT FK_CLIENTES_DIRECCIONES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CEDULA)
)
