CREATE PROCEDURE [dbo].[CREATE_CLIENTES_PR]
	@P_CEDULA	VARCHAR(6),
  @P_NOMBRE			VARCHAR(30),
  @P_APELLIDO		VARCHAR(30),
  @P_GENERO			VARCHAR(1),
  @P_EDAD			NUMERIC(3),
  @P_FECHA_NACIMIENTO DATE,
  @P_ESTADO_CIVIL VARCHAR(1)
AS
	INSERT INTO [dbo].[CLIENTES] VALUES(@P_CEDULA,@P_NOMBRE,@P_APELLIDO,@P_GENERO,@P_EDAD,@P_FECHA_NACIMIENTO,@P_ESTADO_CIVIL);
GO;

CREATE PROCEDURE [dbo].[RETRIEVE_ALL_CLIENTES_PR]
AS
	SELECT CEDULA.CLIENTES, NOMBRE.CLIENTES, APELLIDO.CLIENTES, GENERO.CLIENTES, EDAD.CLIENTES, PROVINCIA.DIRECCIONES, CANTON.DIRECCIONES, DISTRITO.DIRECCIONES
  FROM CLIENTES, DIRECCIONES
  WHERE CEDULA.CLIENTES = ID_CLIENTE.DIRECCIONES;
RETURN 0;

CREATE PROCEDURE [dbo].[RETRIEVE_BY_ID_CLIENTES_PR] @ID_CLIENTE VARCHAR(6)
AS
	SELECT CEDULA.CLIENTES, NOMBRE.CLIENTES, APELLIDO.CLIENTES, GENERO.CLIENTES, EDAD.CLIENTES, PROVINCIA.DIRECCIONES, CANTON.DIRECCIONES, DISTRITO.DIRECCIONES
  FROM CLIENTES, DIRECCIONES
  WHERE CEDULA.CLIENTES = ID_CLIENTE.DIRECCIONES AND CEDULA.CLIENTES = @ID_CLIENTE;
RETURN 0;

CREATE PROCEDURE [dbo].[DELETE_BY_ID_CLIENTES_PR] @ID_CLIENTE VARCHAR(6)
AS
	DELETE FROM CLIENTES
  WHERE CEDULA = @ID_CLIENTE;
RETURN 0;


CREATE PROCEDURE [dbo].[CREATE_CUENTAS_PR]
	@P_ID_CUENTA	VARCHAR(6),
  @P_SALDO		NUMERIC(300),
  @P_MONEDA  VARCHAR(1)
AS
	INSERT INTO [dbo].[CUENTAS] VALUES(@P_ID_CUENTA,@P_SALDO,@P_MONEDA);
GO;

CREATE PROCEDURE [dbo].[RETRIEVE_ALL_CUENTAS_PR]
AS
	SELECT ID_CUENTA, SALDO, MONEDA, ID_CLIENTE FROM CUENTAS;
RETURN 0;

CREATE PROCEDURE [dbo].[RETRIEVE_BY_ID_CUENTAS_PR] @ID_CLIENTE VARCHAR(6)
AS
	SELECT CEDULA.CLIENTES, NOMBRE.CLIENTES, APELLIDO.CLIENTES, ID_CUENTA.CUENTAS, SALDO.CUENTAS, MONEDA.CUENTAS
  FROM CLIENTES, CUENTAS
  WHERE CEDULA.CLIENTES = ID_CLIENTE.CUENTAS AND ID_CLIENTE.CUENTAS = @ID_CLIENTE;
RETURN 0;

CREATE PROCEDURE [dbo].[DELETE_BY_ID_CUENTAS_PR] @ID_CLIENTE VARCHAR(6)
AS
	DELETE FROM CUENTAS
  WHERE ID_CLIENTE = @ID_CLIENTE;
RETURN 0;

CREATE PROCEDURE [dbo].[CREATE_CREDITOS_PR]
	@P_ID_CREDITO	VARCHAR(6),
  @P_ID_CLIENTE	VARCHAR(6),
  @P_NOMBRE			VARCHAR(30),
  @P_MONTO			NUMERIC(300),
  @P_TASA			DECIMAL(10,3),
  @P_CUOTA			DECIMAL(10,3),
  @P_FECHA_INICIO DATE,
  @P_ESTADO   BOOLEAN,
  @P_SALDO_OPERACION	NUMERIC(300)
AS
	INSERT INTO [dbo].[CREDITOS] VALUES(
    @P_ID_CREDITO,@P_ID_CLIENTE,@P_NOMBRE,@P_MONTO,@P_TASA,
    @P_CUOTA,@P_FECHA_INICIO,@P_ESTADO,@P_SALDO_OPERACION);
GO;

CREATE PROCEDURE [dbo].[RETRIEVE_ALL_CREDITOS_PR]
AS
	SELECT ID_CREDITO,ID_CLIENTE,NOMBRE,MONTO,TASA,
    CUOTA,FECHA_INICIO,ESTADO,SALDO_OPERACION FROM CREDITOS;
RETURN 0;

CREATE PROCEDURE [dbo].[RETRIEVE_BY_ID_CREDITOS_PR] @ID_CLIENTE VARCHAR(6)
AS
	SELECT CEDULA.CLIENTES, NOMBRE.CLIENTES, APELLIDO.CLIENTES, NOMBRE.CREDITOS, MONTO.CREDITOS, TASA.CREDITOS
  FROM CLIENTES, CREDITOS
  WHERE CEDULA.CLIENTES = ID_CLIENTE.CREDITOS AND ID_CLIENTE.CREDITOS = @ID_CLIENTE;
RETURN 0;

CREATE PROCEDURE [dbo].[DELETE_BY_ID_CREDITOS_PR] @ID_CLIENTE VARCHAR(6)
AS
	DELETE FROM CREDITOS
  WHERE ID_CLIENTE = @ID_CLIENTE;
RETURN 0;

CREATE PROCEDURE [dbo].[CREATE_DIRECCIONES_PR]
	@P_ID_DIRECCION	VARCHAR(6),
  @P_ID_CLIENTE	VARCHAR(6),
  @P_PROVINCIA			VARCHAR(30),
  @P_CANTON		VARCHAR(30),
  @P_DISTRITO		VARCHAR(30),
AS
	INSERT INTO [dbo].[DIRECCIONES] VALUES(@P_ID_DIRECCION,@P_ID_CLIENTE,@P_PROVINCIA,@P_CANTON,@P_DISTRITO);
GO;

CREATE PROCEDURE [dbo].[RETRIEVE_ALL_DIRECCIONES_PR]
AS
	SELECT ID_DIRECCION,ID_CLIENTE,PROVINCIA,CANTON,DISTRITO FROM DIRECCIONES;
RETURN 0;

CREATE PROCEDURE [dbo].[RETRIEVE_BY_ID_DIRECCIONES_PR] @ID_CLIENTE VARCHAR(6)
AS
	SELECT ID_DIRECCION, PROVINCIA, CANTON, DISTRITO FROM DIRECCIONES
  WHERE ID_CLIENTE = @ID_CLIENTE;
RETURN 0;

CREATE PROCEDURE [dbo].[DELETE_BY_ID_DIRECCIONES_PR] @ID_CLIENTE VARCHAR(6)
AS
	DELETE FROM DIRECCIONES
  WHERE ID_CLIENTE = @ID_CLIENTE;
RETURN 0;




